USE BDDorianOwen;
GO

CREATE PROCEDURE salage
	@NoJoueur	INT ,
	@Mail		VARCHAR(100),
	@Mdp		VARCHAR(50),
	@pReponse NVARCHAR(250) OUTPUT
AS
BEGIN
		SET NOCOUNT ON

		DECLARE @Sel UNIQUEIDENTIFIER=NEWID();
		BEGIN TRY

			INSERT INTO JOUEUR(NoJoueur, Mail, mdp, Sel)
			VALUES (@NoJoueur, HASHBYTES('SHA2_512', @Mdp+CAST(@Sel AS NVARCHAR(36))), 
					@Mail,@Sel);
			SET @pReponse = 'Success';

		END TRY
		BEGIN CATCH
			SET @pReponse = ERROR_MESSAGE();
		END CATCH
END